(function(){function h(b,a){b.getAttribute("tabindex")||b.setAttribute("tabindex","0");b.addEventListener("keydown",function(b){b=b||window.event;switch(b.keyCode){case 33:a.prevNode(10);break;case 34:a.nextNode(10);break;case 35:a.nextNode(-1);break;case 36:a.prevNode(-1);break;case 37:a.prevNode(1);break;case 38:a.nextSibling(-1);break;case 39:a.nextNode(1);break;case 40:a.nextSibling(1);break;case 46:a.cutCurrent()}33<=b.keyCode&&40>=b.keyCode&&b.preventDefault()})}function l(b,a){b.addEventListener("wheel",
function(b){b=b||window.event;0<b.deltaY?(a.nextNode(1),b.preventDefault()):0>b.deltaY&&(a.prevNode(1),b.preventDefault())})}function f(b,a){try{var k=c.parseSgf(b)}catch(e){return}c.loadSgf(k,a)}function n(b,a,c){var e=new XMLHttpRequest;e.onreadystatechange=function(){4===e.readyState&&200===e.status&&(f(e.responseText,a),m(a,c))};e.overrideMimeType("text/plain");e.open("GET",b,!0);e.send()}function m(b,a){function c(a,d){var c;a=a.split(/\D+/);for(c=0;c<a.length;c++)a[c]&&(d?b.getCurrent().children.length&&
(b.nextNode(1),b.nextSibling(a[c]-1)):b.nextNode(+a[c]))}var e,d;a=a.split(/[Nn]+/);for(e=0;e<a.length;e++){var p=a[e].split(/[Bb]+/);c(p[0],!1);for(d=1;d<p.length;d++)c(p[d],!0)}}var c=window.besogo=window.besogo||{};c.VERSION="0.0.2-alpha";c.create=function(b,a){function k(a,c){c&&a>c?(b.style["flex-direction"]="row",r.style.height=c+"px",r.style.width=c+"px",q&&(q.style.height=c+"px",q.style.width=a-c+"px")):(b.style["flex-direction"]="column",r.style.height=a+"px",r.style.width=a+"px",q&&(c&&
(q.style.height=c-a+"px"),q.style.width=a+"px"))}function e(a,c){var d=document.createElement("div");a&&(d.className=a);c=c||b;c.appendChild(d);return d}var d={control:c.makeControlPanel,names:c.makeNamesPanel,comment:c.makeCommentPanel,tool:c.makeToolPanel,tree:c.makeTreePanel,file:c.makeFilePanel},p=b.textContent||b.innerText||"";b.className+=" besogo-container";a=a||{};a.size=c.parseSize(a.size||19);a.coord=a.coord||"none";a.tool=a.tool||"auto";""===a.panels&&(a.panels=[]);a.panels=a.panels||"control+names+comment+tool+tree+file";
"string"===typeof a.panels&&(a.panels=a.panels.split("+"));a.path=a.path||"";void 0===a.shadows?a.shadows="auto":"off"===a.shadows&&(a.shadows=!1);var g=c.makeEditor(a.size.x,a.size.y);g.setTool(a.tool);g.setCoordStyle(a.coord);a.realstones?(g.REAL_STONES=!0,g.SHADOWS=a.shadows):g.SHADOWS=a.shadows&&"auto"!==a.shadows;a.nokeys||h(b,g);if(a.sgf)try{n(a.sgf,g,a.path)}catch(x){}else p.match(/\s*\(\s*;/)&&(f(p,g),m(g,a.path));for("number"!==typeof a.variants&&"string"!==typeof a.variants||g.setVariantStyle(+a.variants);b.firstChild;)b.removeChild(b.firstChild);
var r=e("besogo-board");c.makeBoardDisplay(r,g);a.nowheel||l(r,g);if(0<a.panels.length){var q=e("besogo-panels");for(p=0;p<a.panels.length;p++){var u=a.panels[p];if(d[u])d[u](e("besogo-"+u,q),g)}q.firstChild||(b.removeChild(q),q=!1)}a.resize=a.resize||"auto";"auto"===a.resize?(g=function(){var c=window.innerHeight,d=parseFloat(getComputedStyle(b.parentElement).width),e=+(a.maxwidth||-1),g=a.orient||"auto",p=+(a.portratio||200)/100,l=+(a.landratio||200)/100,f=+(a.minpanelswidth||350),h=+(a.minpanelsheight||
400),n=+(a.transwidth||600);d=0<e&&e<d?e:d;"portrait"!==g&&"landscape"!==g&&(g=d<n||"view"===g&&d<c?"portrait":"landscape");if("portrait"===g){if(!isNaN(p)){var r=p*d;q&&(r=r-d<h?d+h:r)}}else"landscape"===g&&(r=q?isNaN(l)?c:d/l:d,q&&(r=d<r+f?d-f:r));k(d,r);b.style.width=d+"px"},window.addEventListener("resize",g),g()):"fixed"===a.resize&&k(b.clientWidth,b.clientHeight)};c.parseSize=function(b){var a;b=(b+"").replace(/\s/g,"");if(a=b.match(/^(\d+):(\d+)$/)){var c=+a[1];b=+a[2]}else b.match(/^\d+$/)?
(c=+b,b=+b):c=b=19;if(52<c||1>c||52<b||1>b)c=b=19;return{x:c,y:b}};c.autoInit=function(){function b(a,b){return-1!==a.className.split(" ").indexOf(b)}var a=document.getElementsByTagName("div"),k=[],e,d;for(e=0;e<a.length;e++)(b(a[e],"besogo-editor")||b(a[e],"besogo-viewer")||b(a[e],"besogo-diagram"))&&!b(a[e],"besogo-container")&&k.push(a[e]);for(e=0;e<k.length;e++){a={};b(k[e],"besogo-editor")?(a.panels="control names comment tool tree file".split(" "),a.tool="auto"):b(k[e],"besogo-viewer")?(a.panels=
["control","names","comment"],a.tool="navOnly"):b(k[e],"besogo-diagram")&&(a.panels=[],a.tool="navOnly");var p=k[e].attributes;for(d=0;d<p.length;d++)a[p[d].name]=p[d].value;c.create(k[e],a)}}})();
besogo.makeBoardDisplay=function(h,l){function f(){C=!0;A=[];v.removeChild(B);h.removeEventListener("touchstart",f)}function n(d){var g="";x=("none"===d?0:75)+6;var e=2*x+88*w;var p=2*x+88*t;v=besogo.svgEl("svg",{width:"100%",height:"100%",viewBox:"0 0 "+e+" "+p});v.appendChild(besogo.svgEl("rect",{width:e,height:p,"class":"besogo-svg-board"}));v.appendChild(besogo.svgEl("rect",{width:88*(w-1),height:88*(t-1),x:q(1),y:q(1),"class":"besogo-svg-lines"}));for(e=2;e<=t-1;e++)g+="M"+q(1)+","+q(e)+"h"+
88*(w-1);for(e=2;e<=w-1;e++)g+="M"+q(e)+","+q(1)+"v"+88*(t-1);v.appendChild(besogo.svgEl("path",{d:g,"class":"besogo-svg-lines"}));c();"none"!==d&&m(d);y=besogo.svgEl("g");D=besogo.svgEl("g");v.appendChild(y);v.appendChild(D);C||(B=besogo.svgEl("g"),v.appendChild(B));for(g=1;g<=w;g++)for(e=1;e<=t;e++)d=besogo.svgEl("rect",{x:q(g)-44,y:q(e)-44,width:88,height:88,opacity:0}),d.addEventListener("click",b(g,e)),C||(d.addEventListener("mouseover",a(g,e)),d.addEventListener("mouseout",k(g,e))),v.appendChild(d);
if(l.REAL_STONES)for(d=besogo.BLACK_STONES*besogo.WHITE_STONES,E=[],g=1;g<=w;g++)for(e=1;e<=t;e++)E[u(g,e)]=Math.floor(Math.random()*d)}function m(a){function b(a,b,d){a=besogo.svgEl("text",{x:a,y:b,dy:".65ex","font-size":32,"text-anchor":"middle","font-family":"Helvetica, Arial, sans-serif",fill:"black"});a.appendChild(document.createTextNode(d));v.appendChild(a)}var d=besogo.coord[a](w,t),c=d.x,e=d.xb||d.x;a=d.y;d=d.yb||d.y;var g;for(g=1;g<=w;g++){var k=q(g);b(k,q(1)-85,c[g]);b(k,q(t)+85,e[g])}for(g=
1;g<=t;g++)c=q(g),b(q(1)-85,c,a[g]),b(q(w)+85,c,d[g])}function c(){function a(a,d){b+="M"+q(a)+","+q(d)+"l0,0"}var b="";if(w%2&&t%2){var d=(w-1)/2+1;var c=(t-1)/2+1;a(d,c);17<=w&&17<=t&&(a(4,c),a(w-3,c),a(d,4),a(d,t-3))}11<=w&&11<=t?(a(4,4),a(4,t-3),a(w-3,4),a(w-3,t-3)):8<=w&&8<=t&&(a(3,3),a(3,t-2),a(w-2,3),a(w-2,t-2));b&&v.appendChild(besogo.svgEl("path",{d:b,"stroke-linecap":"round","class":"besogo-svg-hoshi"}))}function b(b,d){return function(c){l.click(b,d,c.ctrlKey,c.shiftKey);C||a(b,d)()}}function a(a,
b){return function(){var d=A[u(a,b)];d&&d.setAttribute("visibility","visible")}}function k(a,b){return function(){var d=A[u(a,b)];d&&d.setAttribute("visibility","hidden")}}function e(a){var b=besogo.svgEl("g"),d,c,g;if(l.SHADOWS){var e=besogo.svgShadowGroup();b.appendChild(e)}for(d=1;d<=w;d++)for(c=1;c<=t;c++)if(g=a.getStone(d,c)){var k=q(d);var p=q(c);l.REAL_STONES?b.appendChild(besogo.realStone(k,p,g,E[u(d,c)])):b.appendChild(besogo.svgStone(k,p,g));l.SHADOWS&&(e.appendChild(besogo.svgShadow(k-
2,p-4)),e.appendChild(besogo.svgShadow(k+2,p+4)))}v.replaceChild(b,y);y=b}function d(a){var b,d,c=besogo.svgEl("g"),e=a.move,k=l.getVariants(),f;z=[];for(b=1;b<=w;b++)for(d=1;d<=t;d++)if(f=a.getMarkup(b,d)){var y=q(b);var h=q(d);var r=a.getStone(b,d);var n=-1===r?"white":"black";e&&e.x===b&&e.y===d?n=g(k,a,b,d)?besogo.PURP:besogo.BLUE:g(k,a,b,d)&&(n=besogo.RED);if("number"===typeof f)switch(f){case 1:var m=besogo.svgCircle(y,h,n);break;case 2:m=besogo.svgSquare(y,h,n);break;case 3:m=besogo.svgTriangle(y,
h,n);break;case 4:m=besogo.svgCross(y,h,n);break;case 5:m=besogo.svgBlock(y,h,n)}else r||(m=p(y,h),c.appendChild(m)),m=besogo.svgLabel(y,h,n,f);c.appendChild(m);z[u(b,d)]=m}e&&0!==e.x&&0!==e.y&&(b=e.x,d=e.y,z[u(b,d)]||(n=g(k,a,b,d)?besogo.PURP:besogo.BLUE,m=besogo.svgPlus(q(b),q(d),n),c.appendChild(m),z[u(b,d)]=m));for(b=0;b<k.length;b++)k[b]!==a&&(m=k[b].move)&&0!==m.x&&!z[u(m.x,m.y)]&&(h=a.getStone(m.x,m.y),d=q(m.x),y=q(m.y),h||(h=p(d,y),c.appendChild(h)),h=String.fromCharCode(65+b%26),h=besogo.svgLabel(d,
y,besogo.LRED,h),c.appendChild(h),z[u(m.x,m.y)]=h);v.replaceChild(c,D);D=c}function p(a,b){return besogo.svgEl("rect",{x:a-44,y:b-44,height:88,width:88,opacity:.85,stroke:"none","class":"besogo-svg-board besogo-svg-backer"})}function g(a,b,d,c){var e,g;for(e=0;e<a.length;e++)if(a[e]!==b&&(g=a[e].move)&&g.x===d&&g.y===c)return!0;return!1}function r(a){if(!C){var b,d,c=besogo.svgEl("g"),e=l.getTool(),g;A=[];c.setAttribute("opacity","0.35");if("navOnly"===e)for(a=a.children,b=0;b<a.length;b++){if((g=
a[b].move)&&0!==g.x){var k=q(g.x);var p=q(g.y);var f=besogo.svgStone(k,p,g.color);f.setAttribute("visibility","hidden");c.appendChild(f);A[u(g.x,g.y)]=f}}else for(b=1;b<=w;b++)for(d=1;d<=t;d++){f=null;k=q(b);p=q(d);g=a.getStone(b,d);var h=-1===g?"white":"black";switch(e){case "auto":f=besogo.svgStone(k,p,a.nextMove());break;case "playB":f=besogo.svgStone(k,p,-1);break;case "playW":f=besogo.svgStone(k,p,1);break;case "addB":-1===g?f=besogo.svgCross(k,p,besogo.RED):(f=besogo.svgEl("g"),f.appendChild(besogo.svgStone(k,
p,-1)),f.appendChild(besogo.svgPlus(k,p,besogo.RED)));break;case "addW":1===g?f=besogo.svgCross(k,p,besogo.RED):(f=besogo.svgEl("g"),f.appendChild(besogo.svgStone(k,p,1)),f.appendChild(besogo.svgPlus(k,p,besogo.RED)));break;case "addE":g&&(f=besogo.svgCross(k,p,besogo.RED));break;case "circle":f=besogo.svgCircle(k,p,h);break;case "square":f=besogo.svgSquare(k,p,h);break;case "triangle":f=besogo.svgTriangle(k,p,h);break;case "cross":f=besogo.svgCross(k,p,h);break;case "block":f=besogo.svgBlock(k,p,
h);break;case "label":f=besogo.svgLabel(k,p,h,l.getLabel())}f&&(f.setAttribute("visibility","hidden"),c.appendChild(f),A[u(b,d)]=f)}v.replaceChild(c,B);B=c}}function q(a){return x+44+88*(a-1)}function u(a,b){return(a-1)*t+(b-1)}var x,w=l.getCurrent().getSize().x,t=l.getCurrent().getSize().y,v,y,D,B,z,A,E,C=!1;n(l.getCoordStyle());h.appendChild(v);l.addListener(function(a){var b=l.getCurrent(),c=b.getSize(),g=!1,k=v;if(c.x!==w||c.y!==t||a.coord)w=c.x,t=c.y,n(a.coord||l.getCoordStyle()),h.replaceChild(v,
k),g=!0;g||a.navChange||a.stoneChange?(e(b),d(b),r(b)):a.markupChange||a.treeChange?(d(b),r(b)):(a.tool||a.label)&&r(b)});(function(a){e(a);d(a);r(a)})(l.getCurrent());h.addEventListener("touchstart",f)};
besogo.makeCommentPanel=function(h,l){function f(g){if(g.navChange){var e=l.getCurrent().comment||"";var f=a;e=document.createTextNode(e);f.replaceChild(e,m.C);m.C=e;l.getCurrent()===l.getRoot()&&c.firstChild&&"none"===b.style.display?c.style.display="table":c.style.display="none";k.style.display="none";a.style.display="block"}else void 0!==g.comment&&(f=a,e=document.createTextNode(g.comment),f.replaceChild(e,m.C),m.C=e,k.value=g.comment);if(g.gameInfo){f=g.gameInfo;e=document.createElement("table");
var u;e.className="besogo-gameInfo";for(u=0;u<d.length;u++){var x=d[u];if(f[x]){var w=document.createElement("tr");e.appendChild(w);var t=document.createElement("td");t.appendChild(document.createTextNode(p[x]));w.appendChild(t);t=document.createElement("td");x=document.createTextNode(f[x]);t.appendChild(x);w.appendChild(t)}}e.firstChild&&"none"!==c.style.display||(e.style.display="none");h.replaceChild(e,c);c=e;n(g.gameInfo)}}function n(a){var c=document.createElement("table"),g=e.concat(d),k;c.className=
"besogo-gameInfo";for(k=0;k<g.length;k++){var f=g[k];var n=document.createElement("tr");c.appendChild(n);var m=document.createElement("td");m.appendChild(document.createTextNode(p[f]));n.appendChild(m);m=document.createElement("td");var v=document.createElement("input");a[f]&&(v.value=a[f]);v.onblur=function(a,b){return function(){l.setGameInfo(a.value,b)}}(v,f);v.addEventListener("keydown",function(a){a=a||window.event;a.stopPropagation()});m.appendChild(v);n.appendChild(m)}"none"===b.style.display&&
(c.style.display="none");h.replaceChild(c,b);b=c}var m={},c=document.createElement("table"),b=document.createElement("table"),a=document.createElement("div"),k=document.createElement("textarea"),e="PW WR WT PB BR BT".split(" "),d="HA KM RU TM OT GN EV PC RO DT RE ON GC AN US SO CP".split(" "),p={PW:"White Player",WR:"White Rank",WT:"White Team",PB:"Black Player",BR:"Black Rank",BT:"Black Team",HA:"Handicap",KM:"Komi",RU:"Rules",TM:"Timing",OT:"Overtime",GN:"Game Name",EV:"Event",PC:"Place",RO:"Round",
DT:"Date",RE:"Result",ON:"Opening",GC:"Comments",AN:"Annotator",US:"Recorder",SO:"Source",CP:"Copyright"};h.appendChild(function(){var a=document.createElement("input");a.type="button";a.value="Info";a.title="Show/hide game info";a.onclick=function(){c.style.display="none"===c.style.display&&c.firstChild?"table":"none";b.style.display="none"};return a}());h.appendChild(function(){var a=document.createElement("input");a.type="button";a.value="Edit Info";a.title="Edit game info";a.onclick=function(){b.style.display=
"none"===b.style.display?"table":"none";c.style.display="none"};return a}());h.appendChild(function(){var b=document.createElement("input");b.type="button";b.value="Comment";b.title="Edit comment";b.onclick=function(){"none"===k.style.display?(a.style.display="none",c.style.display="none",k.value=l.getCurrent().comment,k.style.display="block"):(k.style.display="none",a.style.display="block")};return b}());h.appendChild(c);h.appendChild(b);m.C=document.createTextNode("");h.appendChild(a);a.appendChild(m.C);
h.appendChild(k);k.onblur=function(){l.setComment(k.value)};k.addEventListener("keydown",function(a){a=a||window.event;a.stopPropagation()});l.addListener(f);f({navChange:!0,gameInfo:l.getGameInfo()});b.style.display="none"};
besogo.makeControlPanel=function(h,l){function f(g){function f(b){b%2?(e.setAttribute("fill","black"),d.setAttribute("fill",besogo.BLUE),a.title="Variants: child/[sibling]"):(e.setAttribute("fill",besogo.BLUE),d.setAttribute("fill",besogo.RED),a.title="Variants: [child]/sibling");2<=b?(p.setAttribute("visibility","visible"),k.title="Variants: show/[hide]"):(p.setAttribute("visibility","hidden"),k.title="Variants: [show]/hide")}function q(a,b){var d;for(d=0;d<a.length;d++)a[d].setAttribute("fill",
b)}void 0!==g.variantStyle&&f(g.variantStyle);if(g.navChange||g.treeChange)g=l.getCurrent(),g.parent?(q(m,"black"),1<g.parent.children.length?q(b,"black"):q(b,besogo.GREY)):(q(m,besogo.GREY),q(b,besogo.GREY)),g.children.length?q(c,"black"):q(c,besogo.GREY)}function n(){return besogo.svgEl("svg",{width:"100%",height:"100%",viewBox:"0 0 100 100"})}var m=[],c=[],b=[],a,k,e,d,p;(function(){function a(a,b,d){var c=document.createElement("button"),e=n();b=besogo.svgEl("polygon",{points:b,stroke:"none",
fill:"black"});c.title=a;c.onclick=d;c.appendChild(e);e.appendChild(b);h.appendChild(c);return b}m.push(a("First node","5,10 5,90 25,90 25,50 95,90 95,10 25,50 25,10",function(){l.prevNode(-1)}));m.push(a("Jump back","95,10 50,50 50,10 5,50 50,90 50,50 95,90",function(){l.prevNode(10)}));m.push(a("Previous node","85,10 85,90 15,50",function(){l.prevNode(1)}));c.push(a("Next node","15,10 15,90 85,50",function(){l.nextNode(1)}));c.push(a("Jump forward","5,10 50,50 50,10 95,50 50,90 50,50 5,90",function(){l.nextNode(10)}));
c.push(a("Last node","95,10 95,90 75,90 75,50 5,90 5,10 75,50 75,10",function(){l.nextNode(-1)}));b.push(a("Previous sibling","10,85 90,85 50,15",function(){l.nextSibling(-1)}));b.push(a("Next sibling","10,15 90,15 50,85",function(){l.nextSibling(1)}))})();(function(){a=document.createElement("button");a.onclick=function(){l.toggleVariantStyle(!1)};h.appendChild(a);var b=n();a.appendChild(b);var c=besogo.svgEl("path",{d:"m75,25h-50l50,50",stroke:"black","stroke-width":5,fill:"none"});b.appendChild(c);
e=besogo.svgEl("circle",{cx:25,cy:25,r:20,stroke:"none"});b.appendChild(e);d=besogo.svgEl("circle",{cx:75,cy:25,r:20,stroke:"none"});b.appendChild(d);c=besogo.svgEl("circle",{cx:75,cy:75,r:20,fill:besogo.RED,stroke:"none"});b.appendChild(c);k=document.createElement("button");k.onclick=function(){l.toggleVariantStyle(!0)};h.appendChild(k);b=n();k.appendChild(b);b.appendChild(besogo.svgLabel(50,50,besogo.RED,"A"));p=besogo.svgCross(50,50,"black");b.appendChild(p);c=document.createElement("button");
c.onclick=function(){l.toggleCoordStyle()};c.title="Toggle coordinates";h.appendChild(c);b=n();c.appendChild(b);b.appendChild(besogo.svgLabel(50,50,"black","\u56db4"))})();l.addListener(f);f({navChange:!0,variantStyle:l.getVariantStyle()})};
(function(){function h(f){return"ABCDEFGHJKLMNOPQRSTUVWXYZ".charAt((f-1)%25)}function l(f){var l="";20<=f?l="\u4e00\u4e8c\u4e09\u56db\u4e94\u516d\u4e03\u516b\u4e5d".charAt(f/10-1)+"\u5341":10<=f&&(l="\u5341");f%10&&(l+="\u4e00\u4e8c\u4e09\u56db\u4e94\u516d\u4e03\u516b\u4e5d".charAt((f-1)%10));return l}besogo.coord={};besogo.coord.none=function(f,l){return!1};besogo.coord.western=function(f,l){var m={x:[],y:[]},c;for(c=1;c<=f;c++)m.x[c]=h(c);for(c=1;c<=l;c++)m.y[c]=l-c+1+"";return m};besogo.coord.numeric=
function(f,l){var h={x:[],y:[]},c;for(c=1;c<=f;c++)h.x[c]=c+"";for(c=1;c<=l;c++)h.y[c]=c+"";return h};besogo.coord.pierre=function(f,l){var h={x:[],xb:[],y:[],yb:[]},c;for(c=1;c<=f/2;c++)h.x[c]="a"+c,h.x[f-c+1]="b"+c,h.xb[c]="d"+c,h.xb[f-c+1]="c"+c;f%2&&(c=Math.ceil(f/2),h.x[c]="a",h.xb[c]="c");for(c=1;c<=l/2;c++)h.y[c]="a"+c,h.y[l-c+1]="d"+c,h.yb[c]="b"+c,h.yb[l-c+1]="c"+c;l%2&&(c=Math.ceil(l/2),h.y[c]="d",h.yb[c]="b");return h};besogo.coord.corner=function(f,l){var m={x:[],y:[]},c;for(c=1;c<=f;c++)m.x[c]=
c<f/2+1?h(c):f-c+1+"";for(c=1;c<=l;c++)m.y[c]=l-c+1+"",m.y[c]=c>l/2?h(l-c+1):c+"";return m};besogo.coord.eastcor=function(f,h){var m={x:[],y:[]},c;for(c=1;c<=f;c++)m.x[c]=c<f/2+1?l(c):f-c+1+"";for(c=1;c<=h;c++)m.y[c]=h-c+1+"",m.y[c]=c>h/2?l(h-c+1):c+"";return m};besogo.coord.eastern=function(f,h){var m={x:[],y:[]},c;for(c=1;c<=f;c++)m.x[c]=c+"";for(c=1;c<=h;c++)m.y[c]=l(c);return m}})();
besogo.makeEditor=function(h,l){function f(a){"string"===typeof a&&(q=(a=a.replace(/\s/g," ").trim())||"1",r="label",k({tool:r,label:q}))}function n(a,b,c){var g,p=d.children;for(g=0;g<p.length;g++){var f=p[g].move;if(c){if(m(a,b,p[g]))return!0}else if(f&&f.x===a&&f.y===b)return d=p[g],k({navChange:!0}),!0}return c&&m(a,b,e,d)?!0:!1}function m(a,b,c,e){var g,p=c.children;if(e&&e===c)return!1;if((g=c.move)&&g.x===a&&g.y===b)return d=c,k({navChange:!0}),!0;for(c=0;c<p.length;c++)if(m(a,b,p[c],e))return!0;
return!1}function c(a,b,c,e){if(d.isMutable("move")&&d.parent)d.playMove(a,b,c,e)&&k({stoneChange:!0});else{var g=d.makeChild();g.playMove(a,b,c,e)&&(d.addChild(g),d=g,k({treeChange:!0,navChange:!0,stoneChange:!0}))}}function b(a,b,c){if(c===d.getStone(a,b))if(0!==c)c=0;else return;if(d.isMutable("setup"))d.placeSetup(a,b,c)&&k({stoneChange:!0});else{var e=d.makeChild();e.placeSetup(a,b,c)&&(d.addChild(e),d=e,k({treeChange:!0,navChange:!0,stoneChange:!0}))}}function a(a,b,c){if(c===d.getMarkup(a,
b))if(0!==c)c=0;else return;d.addMarkup(a,b,c)&&("string"===typeof c&&(/^-?\d+$/.test(c)?f(""+(+c+1)):/[A-Za-z]$/.test(c)&&(a=c.charAt(c.length-1),a="z"===a?"A":"Z"===a?"a":String.fromCharCode(a.charCodeAt()+1),f(c.slice(0,c.length-1)+a))),k({markupChange:!0}))}function k(a,b){var c;!b&&a.navChange&&(u=[]);for(c=0;c<p.length;c++)p[c](a)}var e=besogo.makeGameRoot(h,l),d=e,p=[],g="navOnly auto playB playW addB addW addE clrMark circle square triangle cross block label".split(" "),r="auto",q="1",u=[],
x={},w="none numeric western eastern pierre corner eastcor".split(" "),t="none",v=0;return{addListener:function(a){p.push(a)},click:function(d,e,k,g){switch(r){case "navOnly":n(d,e,g);break;case "auto":n(d,e,g)||g||c(d,e,0,k);break;case "playB":c(d,e,-1,k);break;case "playW":c(d,e,1,k);break;case "addB":k?c(d,e,-1,!0):b(d,e,-1);break;case "addW":k?c(d,e,1,!0):b(d,e,1);break;case "addE":b(d,e,0);break;case "clrMark":a(d,e,0);break;case "circle":a(d,e,1);break;case "square":a(d,e,2);break;case "triangle":a(d,
e,3);break;case "cross":a(d,e,4);break;case "block":a(d,e,5);break;case "label":a(d,e,q)}},nextNode:function(a){if(0===d.children.length)return!1;for(;0<d.children.length&&0!==a;)d=u.length?u.pop():d.children[0],a--;k({navChange:!0},!0)},prevNode:function(a){if(null===d.parent)return!1;for(;d.parent&&0!==a;)u.push(d),d=d.parent,a--;k({navChange:!0},!0)},nextSibling:function(a){if(d.parent){var b=d.parent.children;if(1!==b.length){var c=b.indexOf(d);c=(c+a)%b.length;0>c&&(c+=b.length);d=b[c];k({navChange:!0})}}},
toggleCoordStyle:function(){t=w[(w.indexOf(t)+1)%w.length];k({coord:t})},getCoordStyle:function(){return t},setCoordStyle:function(a){besogo.coord[a]&&(t=a,k({coord:a}))},toggleVariantStyle:function(a){var b=v%2,c=v-b;a?c=(c+2)%4:b=(b+1)%2;v=b+c;k({variantStyle:v,markupChange:!0})},getVariantStyle:function(){return v},setVariantStyle:function(a){if(0===a||1===a||2===a||3===a)v=a,k({variantStyle:v,markupChange:!0})},getGameInfo:function(){return x},setGameInfo:function(a,b){b?x[b]=a:x=a;k({gameInfo:x})},
setComment:function(a){a=a.trim();a=a.replace(/\r\n/g,"\n").replace(/\n\r/g,"\n").replace(/\r/g,"\n");a.replace(/\f\t\v\u0085\u00a0/g," ");d.comment=a;k({comment:a})},getTool:function(){return r},setTool:function(a){return"label"===a&&a===r?(/^-?\d+$/.test(q)?f("A"):f("1"),!0):-1!==g.indexOf(a)&&r!==a?(r=a,k({tool:r,label:q}),!0):!1},getLabel:function(){return q},setLabel:f,getVariants:function(){return 2<=v?[]:1===v?d.parent?d.parent.children:[]:d.children},getCurrent:function(){return d},setCurrent:function(a){d!==
a&&(d=a,k({navChange:!0}))},cutCurrent:function(){var a=d.parent;"navOnly"!==r&&a&&!0===confirm("Delete this branch?")&&(a.removeChild(d),d=a,k({treeChange:!0,navChange:!0}))},promote:function(){"navOnly"!==r&&d.parent&&d.parent.promote(d)&&k({treeChange:!0})},demote:function(){"navOnly"!==r&&d.parent&&d.parent.demote(d)&&k({treeChange:!0})},getRoot:function(){return e},loadRoot:function(a){d=e=a;k({treeChange:!0,navChange:!0,stoneChange:!0})}}};
besogo.makeFilePanel=function(h,l){function f(a){var b=document.createElement("input");b.type="button";b.value=a+"x"+a;"?"===a?(b.title="New custom size board",b.onclick=function(){var a=prompt("Enter custom size for new board\nEverything not saved will be lost","19:19");a&&(a=besogo.parseSize(a),l.loadRoot(besogo.makeGameRoot(a.x,a.y)),l.setGameInfo({}))}):(b.title="New "+a+"x"+a+" board",b.onclick=function(){confirm(b.title+"?\nEverything not saved will be lost")&&(l.loadRoot(besogo.makeGameRoot(a,
a)),l.setGameInfo({}))});h.appendChild(b)}function n(){var a=document.createElement("input");a.type="file";a.style.display="none";a.onchange=m;return a}function m(a){a=a.target.files[0];var b=new FileReader,e=n();h.replaceChild(e,c);c=e;b.onload=function(a){try{var b=besogo.parseSgf(a.target.result)}catch(g){alert("SGF parse error at "+g.at+":\n"+g.message);return}besogo.loadSgf(b,l)};confirm("Load '"+a.name+"'?\nEverything not saved will be lost")&&b.readAsText(a)}f(9);f(13);f(19);f("?");var c=n();
h.appendChild(c);var b=document.createElement("input");b.type="button";b.value="Open";b.title="Import SGF";b.onclick=function(){c.click()};h.appendChild(b);b=document.createElement("input");b.type="button";b.value="Save";b.title="Export SGF";b.onclick=function(){var a=prompt("Save file as","export.sgf");if(a){var b=besogo.composeSgf(l),c=document.createElement("a");b=new Blob([b],{encoding:"UTF-8",type:"text/plain;charset=UTF-8"});c.download=a;c.href=URL.createObjectURL(b);c.style.display="none";
h.appendChild(c);c.click();h.removeChild(c)}};h.appendChild(b)};
besogo.makeGameRoot=function(h,l){function f(b,a){b.parent=a;b.children=[];b.move=null;b.setupStones=[];b.markup=[];b.comment=""}function n(b,a,c,e,d){var k=[];if(!m(b,a,c,e,k))for(a=0;a<k.length;a++)b["board"+k[a].x+"-"+k[a].y]=0,d.push(k[a])}function m(b,a,c,e,d){var k;if(1>a||1>c||a>h||c>l||b.getStone(a,c)===e)return!1;if(!b.getStone(a,c))return!0;for(k=0;k<d.length;k++)if(d[k].x===a&&d[k].y===c)return!1;d.push({x:a,y:c});return m(b,a-1,c,e,d)||m(b,a+1,c,e,d)||m(b,a,c-1,e,d)||m(b,a,c+1,e,d)?!0:
!1}var c={blackCaps:0,whiteCaps:0,moveNumber:0};f(c,null);c.playMove=function(b,a,c,e){var d=!1;if(!this.isMutable("move"))return!1;c||(c=this.nextMove());if(1>b||1>a||b>h||a>l)return this.move={x:0,y:0,color:c,captures:0,overwrite:!1},this.lastMove=c,this.moveNumber++,!0;if(this.getStone(b,a)){if(!e)return!1;d=!0}var k=Object.create(this);var g=[];k["board"+b+"-"+a]=c;n(k,b-1,a,c,g);n(k,b+1,a,c,g);n(k,b,a-1,c,g);n(k,b,a+1,c,g);var f=g.length;var q=this.parent?this.parent.move:null;if(!e&&q&&q.color===
-c&&!1===q.overwrite&&1===q.captures&&1===f&&!k.getStone(q.x,q.y)||0===f&&(n(k,b,a,-c,g),f=-g.length,0>f&&!e))return!1;0>c*f?this.blackCaps+=Math.abs(f):this.whiteCaps+=Math.abs(f);this["board"+b+"-"+a]=c;for(e=0;e<g.length;e++)this["board"+g[e].x+"-"+g[e].y]=0;this.move={x:b,y:a,color:c,captures:f,overwrite:d};this.lastMove=c;this.moveNumber++;return!0};c.nextMove=function(){var b,a,c=0;if(this.lastMove)return-this.lastMove;for(b=1;b<=h;b++)for(a=1;a<=l;a++)c+=this.getStone(b,a);return 0>c?1:-1};
c.placeSetup=function(b,a,c){var e=this.parent&&this.parent.getStone(b,a)||0;if(1>b||1>a||b>h||a>l||!this.isMutable("setup")||this.getStone(b,a)===c)return!1;this["board"+b+"-"+a]=c;this.setupStones[(b-1)*l+(a-1)]=c-e;return!0};c.addMarkup=function(b,a,c){if(1>b||1>a||b>h||a>l||this.getMarkup(b,a)===c)return!1;this.markup[(b-1)*l+(a-1)]=c;return!0};c.getStone=function(b,a){return this["board"+b+"-"+a]||0};c.getSetup=function(b,a){if(this.setupStones[(b-1)*l+(a-1)])switch(this.getStone(b,a)){case 0:return"AE";
case -1:return"AB";case 1:return"AW"}else return!1};c.getMarkup=function(b,a){return this.markup[(b-1)*l+(a-1)]||0};c.getType=function(){var b;if(this.move)return"move";for(b=0;b<this.setupStones.length;b++)if(this.setupStones[b])return"setup";return"empty"};c.isMutable=function(b){return"move"===b&&"empty"===this.getType()&&0===this.children.length||"setup"===b&&"move"!==this.getType()&&0===this.children.length?!0:!1};c.getSiblings=function(){return this.parent&&this.parent.children||[]};c.makeChild=
function(){var b=Object.create(this);f(b,this);return b};c.addChild=function(b){this.children.push(b)};c.removeChild=function(b){b=this.children.indexOf(b);return-1!==b?(this.children.splice(b,1),!0):!1};c.promote=function(b){var a=this.children.indexOf(b);return 0<a?(this.children[a]=this.children[a-1],this.children[a-1]=b,!0):!1};c.demote=function(b){var a=this.children.indexOf(b);return-1!==a&&a<this.children.length-1?(this.children[a]=this.children[a+1],this.children[a+1]=b,!0):!1};c.getSize=
function(){return{x:h,y:l}};return c};
besogo.loadSgf=function(h,l){function f(a,b){var c;for(c=0;c<a.props.length;c++){var e=b;var g=a.props[c];switch(g.id){case "B":g=m(g.values[0]);e.playMove(g.x,g.y,-1,!0);break;case "W":g=m(g.values[0]);e.playMove(g.x,g.y,1,!0);break;case "AB":n(g.values,e,"placeSetup",-1);break;case "AW":n(g.values,e,"placeSetup",1);break;case "AE":n(g.values,e,"placeSetup",0);break;case "CR":n(g.values,e,"addMarkup",1);break;case "SQ":n(g.values,e,"addMarkup",2);break;case "TR":n(g.values,e,"addMarkup",3);break;
case "M":case "MA":n(g.values,e,"addMarkup",4);break;case "SL":n(g.values,e,"addMarkup",5);break;case "L":case "LB":n(g.values,e,"addMarkup","label");break;case "C":e.comment=e.comment?e.comment+("\n"+g.values.join().trim()):g.values.join().trim()}}for(c=0;c<a.children.length;c++)e=b.makeChild(),b.addChild(e),f(a.children[c],e)}function n(a,b,c,f){var d,e;for(d=0;d<a.length;d++){var k=m(a[d].slice(0,2));if("label"===f){var h=a[d].slice(3).replace(/\n/g," ");b[c](k.x,k.y,h)}else if(":"===a[d].charAt(2)){var l=
m(a[d].slice(3));if(l.x===k.x&&l.y===k.y)b[c](k.x,k.y,f);else if(l.x<k.x||l.y<k.y)b[c](k.x,k.y,f),b[c](l.x,l.y,f);else for(h=k.x;h<=l.x;h++)for(e=k.y;e<=l.y;e++)b[c](h,e,f)}else b[c](k.x,k.y,f)}}function m(a){return a.match(/^[A-Za-z]{2}$/)?{x:c(a.charAt(0)),y:c(a.charAt(1))}:{x:0,y:0}}function c(a){return a.match(/[A-Z]/)?a.charCodeAt(0)-65+27:a.charCodeAt(0)-97+1}var b={x:19,y:19};(function(a){var c="PB BR BT PW WR WT HA KM RU TM OT DT EV GN PC RO GC ON RE AN CP SO US".split(" "),d={},f;for(f=0;f<
a.props.length;f++){var g=a.props[f].id;var k=a.props[f].values.join().trim();"SZ"===g?b=besogo.parseSize(k):"ST"===g?l.setVariantStyle(+k):-1!==c.indexOf(g)&&("GC"!==g&&(k=k.replace(/\n/g," ")),k&&(d[g]=k))}l.setGameInfo(d)})(h);var a=besogo.makeGameRoot(b.x,b.y);f(h,a);l.loadRoot(a)};
besogo.makeNamesPanel=function(h,l){function f(f){var g=0;if(f.gameInfo){var h=(f.gameInfo.PW||"White")+" ("+(f.gameInfo.WR||"?")+")"+(f.gameInfo.WT?" "+f.gameInfo.WT:"");h=document.createTextNode(h);c.replaceChild(h,a);a=h;h=(f.gameInfo.PB||"Black")+" ("+(f.gameInfo.BR||"?")+")"+(f.gameInfo.BT?" "+f.gameInfo.BT:"");h=document.createTextNode(h);b.replaceChild(h,k);k=h}if(f.navChange||f.stoneChange)f=l.getCurrent(),f.move&&0===f.move.x&&0===f.move.y&&(g=f.move.color),n(e,(1===g?"Passed  ":"")+f.whiteCaps),
n(d,f.blackCaps+(-1===g?"  Passed":""))}function n(a,b){for(var c=document.createTextNode(b);a.firstChild;)a.removeChild(a.firstChild);a.appendChild(c)}var m=document.createElement("div"),c=document.createElement("div"),b=document.createElement("div"),a=document.createTextNode(""),k=document.createTextNode(""),e=document.createElement("span"),d=document.createElement("span");m.className="besogo-playerInfo";c.className="besogo-whiteInfo";b.className="besogo-blackInfo";e.className="besogo-whiteCaps";
e.title="White captures";d.className="besogo-blackCaps";d.title="Black captures";c.appendChild(a);c.appendChild(e);b.appendChild(k);b.appendChild(d);m.appendChild(c);m.appendChild(b);h.appendChild(m);l.addListener(f);f({navChange:!0,gameInfo:l.getGameInfo()})};
besogo.parseSgf=function(h){function l(a){throw{name:"Syntax Error",message:a,at:k,text:h};}function f(a){a&&a!==e&&l("Expected '"+a+"' instead of '"+e+"'");k++;return e=h.charAt(k)}function n(){for(;e&&" ">=e;)f()}function m(){return"\n"===e?("\r"===h.charAt(k+1)&&f(),!0):"\r"===e?("\n"===h.charAt(k+1)&&f(),!0):!1}function c(){var a;f("(");n();";"!==e&&l("Sub-tree missing root");var k=b();n();for(a=k;";"===e;){var g=b();a.children.push(g);a=g;n()}for(;"("===e;)g=c(),a.children.push(g),n();f(")");
return k}function b(){var b,c={props:[],children:[]};f(";");for(n();e&&";"!==e&&"("!==e&&")"!==e;){for(b={id:"",values:[]};e&&/[A-Za-z]/.test(e);)/[A-Z]/.test(e)&&(b.id+=e),f();b.id||l("Missing property ID");for(n();"["===e;)b.values.push(a()),n();0===b.values.length&&l("Missing property values");c.props.push(b);n()}return c}function a(){var a="";for(f("[");e&&"]"!==e;)"\\"===e?(f("\\"),m()||(a=" ">=e?a+" ":a+e)):a=m()?a+"\n":" ">=e?a+" ":a+e,f();f("]");return a}for(var k=0,e=h.charAt(k);e&&"("!==
e;)f();return c()};
besogo.composeSgf=function(h){function l(b){var a=";",c=b.children;if(!b.parent){var e="FF[4]GM[1]CA[UTF-8]AP[besogo:"+besogo.VERSION+"]",d=b.getSize().x,p=b.getSize().y,g=h.getGameInfo(),r=!1;e=(d===p?e+("SZ["+d+"]"):e+("SZ["+d+":"+p+"]"))+("ST["+h.getVariantStyle()+"]\n");for(q in g)g.hasOwnProperty(q)&&g[q]&&(e+=q+"["+n(g[q])+"]",r=!0);a+=e+(r?"\n":"")}var q=a;a="";if("move"===b.getType())d=b.move,a+=1===d.color?"W":"B",a+="["+m(d.x,d.y)+"]";else if("setup"===b.getType()){e={AB:[],AW:[],AE:[]};
for(p=1;p<=b.getSize().x;p++)for(g=1;g<=b.getSize().y;g++)(d=b.getSetup(p,g))&&e[d].push({x:p,y:g});a+=f(e)}e={CR:[],SQ:[],TR:[],MA:[],SL:[],LB:[]};for(p=1;p<=b.getSize().x;p++)for(g=1;g<=b.getSize().y;g++)if(d=b.getMarkup(p,g))"string"===typeof d?e.LB.push({x:p,y:g,label:d}):(d=["CR","SQ","TR","MA","SL"][d-1],e[d].push({x:p,y:g}));a+=f(e);b.comment&&(a=a+(a?"\n":"")+("C["+n(b.comment)+"]"));a=q+a;if(1===c.length)a+="\n"+l(c[0]);else if(1<c.length)for(b=0;b<c.length;b++)a+="\n("+l(c[b])+")";return a}
function f(b){var a="",c,e;for(c in b)if(b.hasOwnProperty(c)){var d=b[c];if(0<d.length)for(a+=c,e=0;e<d.length;e++)a+="["+m(d[e].x,d[e].y),d[e].label&&(a+=":"+n(d[e].label)),a+="]"}return a}function n(b){b=b.replace(/\\/g,"\\\\");return b.replace(/\]/g,"\\]")}function m(b,a){return 0===b||0===a?"":c(b)+c(a)}function c(b){return 26<b?String.fromCharCode(65+b-27):String.fromCharCode(97+b-1)}return"("+l(h.getRoot())+")"};
(function(){besogo.RED="#be0119";besogo.LRED="#ff474c";besogo.BLUE="#0165fc";besogo.PURP="#9a0eea";besogo.GREY="#929591";besogo.GOLD="#dbb40c";besogo.TURQ="#06c2ac";besogo.BLACK_STONES=4;besogo.WHITE_STONES=11;besogo.svgEl=function(h,l){var f,n=document.createElementNS("http://www.w3.org/2000/svg",h);for(f in l||{})l.hasOwnProperty(f)&&n.setAttribute(f,l[f]);return n};besogo.svgShadowGroup=function(){var h=besogo.svgEl("g"),l=besogo.svgEl("filter",{id:"blur"}),f=besogo.svgEl("feGaussianBlur",{"in":"SourceGraphic",
stdDeviation:"2"});l.appendChild(f);h.appendChild(l);return h};besogo.svgShadow=function(h,l){return besogo.svgEl("circle",{cx:h,cy:l,r:43,stroke:"none",fill:"black",opacity:.32,filter:"url(#blur)"})};besogo.realStone=function(h,l,f,n){f=0>f?"black"+n%besogo.BLACK_STONES:"white"+n%besogo.WHITE_STONES;f="/img/"+f+".png";h=besogo.svgEl("image",{x:h-44,y:l-44,height:88,width:88});h.setAttributeNS("http://www.w3.org/1999/xlink","href",f);return h};besogo.svgStone=function(h,l,f){var n="besogo-svg-greyStone";
-1===f?n="besogo-svg-blackStone":1===f&&(n="besogo-svg-whiteStone");return besogo.svgEl("circle",{cx:h,cy:l,r:42,"class":n})};besogo.svgCircle=function(h,l,f){return besogo.svgEl("circle",{cx:h,cy:l,r:27,stroke:f,"stroke-width":8,fill:"none"})};besogo.svgSquare=function(h,l,f){return besogo.svgEl("rect",{x:h-23,y:l-23,width:46,height:46,stroke:f,"stroke-width":8,fill:"none"})};besogo.svgTriangle=function(h,l,f){return besogo.svgEl("polygon",{points:""+h+","+(l-30)+" "+(h-26)+","+(l+15)+" "+(h+26)+
","+(l+15),stroke:f,"stroke-width":8,fill:"none"})};besogo.svgCross=function(h,l,f){return besogo.svgEl("path",{d:"m"+(h-24)+","+(l-24)+"l48,48m0,-48l-48,48",stroke:f,"stroke-width":8,fill:"none"})};besogo.svgPlus=function(h,l,f){return besogo.svgEl("path",{d:"m"+h+","+(l-28)+"v56m-28,-28h56",stroke:f,"stroke-width":8,fill:"none"})};besogo.svgBlock=function(h,l,f){return besogo.svgEl("rect",{x:h-18,y:l-18,width:36,height:36,stroke:"none","stroke-width":8,fill:f})};besogo.svgLabel=function(h,l,f,n){3<
n.length&&(n=n.slice(0,2)+"\u2026");switch(n.length){case 1:var m=72;break;case 2:m=56;break;case 3:m=36}h=besogo.svgEl("text",{x:h,y:l,dy:".65ex","font-size":m,"text-anchor":"middle","font-family":"Helvetica, Arial, sans-serif",fill:f});h.appendChild(document.createTextNode(n));return h}})();
besogo.makeToolPanel=function(h,l){function f(a,b){var d=document.createElement("button"),e=besogo.svgEl("svg",{width:"100%",height:"100%",viewBox:"-55 -55 110 110"}),f=besogo.svgEl("rect",{x:-50,y:-50,width:100,height:100,fill:"none","stroke-width":8,stroke:besogo.GOLD,rx:20,ry:20,visibility:"hidden"});h.appendChild(d);d.appendChild(e);d.onclick=function(){l.setTool(a)};d.title=b;c[a]=f;e.appendChild(f);return e}function n(a,b,c){var d=document.createElement("input");d.type="button";d.value=a;d.title=
b;d.onclick=c;h.appendChild(d)}function m(a){var b;a.label&&(k.value=a.label);if(a.tool)for(b in c)c.hasOwnProperty(b)&&(a.tool===b?c[b].setAttribute("visibility","visible"):c[b].setAttribute("visibility","hidden"))}var c={};var b=f("auto","Auto-play/navigate\ncrtl+click to force ko, suicide, overwrite\nshift+click to jump to move");b.appendChild(function(a,b){var c=besogo.svgEl("g");c.appendChild(besogo.svgEl("path",{d:"m"+a+","+(b-44)+" a44 44 0 0 1 0,88z",stroke:"none",fill:"black"}));c.appendChild(besogo.svgEl("path",
{d:"m"+a+","+(b+44)+"a44 44 0 0 1 0,-88a22 22 0 0 1 0,44z",stroke:"none",fill:"white"}));c.appendChild(besogo.svgEl("circle",{cx:a,cy:b+22,r:22,stroke:"none",fill:"black"}));return c}(0,0));b=f("addB","Set black\nctrl+click to play");var a=besogo.svgEl("g");a.appendChild(besogo.svgStone(0,0,-1));b.appendChild(a);b=f("addW","Set white\nctrl+click to play");a=besogo.svgEl("g");a.appendChild(besogo.svgStone(0,0,1));b.appendChild(a);b=f("addE","Set empty point");a=besogo.svgEl("g");a.appendChild(besogo.svgStone(0,
0));a.appendChild(besogo.svgCross(0,0,besogo.RED));b.appendChild(a);b=f("circle","Circle");b.appendChild(besogo.svgCircle(0,0,"black"));b=f("square","Square");b.appendChild(besogo.svgSquare(0,0,"black"));b=f("triangle","Triangle");b.appendChild(besogo.svgTriangle(0,0,"black"));b=f("cross","Cross");b.appendChild(besogo.svgCross(0,0,"black"));b=f("block","Block");b.appendChild(besogo.svgBlock(0,0,"black"));b=f("clrMark","Clear mark");a=besogo.svgEl("g");a.appendChild(besogo.svgTriangle(0,0,besogo.GREY));
a.appendChild(besogo.svgCross(0,0,besogo.RED));b.appendChild(a);b=f("label","Label");b.appendChild(besogo.svgLabel(0,0,"black","A1"));var k=document.createElement("input");k.type="text";k.title="Next label";k.onblur=function(){l.setLabel(k.value)};k.addEventListener("keydown",function(a){a=a||window.event;a.stopPropagation()});h.appendChild(k);n("Pass","Pass move",function(){var a=l.getTool();"navOnly"!==a&&"auto"!==a&&"playB"!==a&&"playW"!==a&&l.setTool("auto");l.click(0,0,!1)});n("Raise","Raise variation",
function(){l.promote()});n("Lower","Lower variation",function(){l.demote()});n("Cut","Remove branch",function(){l.cutCurrent()});l.addListener(m);m({label:l.getLabel(),tool:l.getTool()})};
besogo.makeTreePanel=function(h,l){function f(a){var b=h.clientWidth,c=h.clientHeight,d=h.scrollTop,e=h.scrollLeft,f=.25*(a.getAttribute("x")-5),k=.25*(a.getAttribute("y")-5);f<e?h.scrollLeft=f:f+30>e+b&&(h.scrollLeft=f+30-b);k<d?h.scrollTop=k:k+30>d+c&&(h.scrollTop=k+30-c);a.setAttribute("opacity",1);a.onmouseover=null;a.onmouseout=null;g.appendChild(a);r=a}function n(a){a.setAttribute("opacity",0);a.onmouseover=function(){a.setAttribute("opacity",.5)};a.onmouseout=function(){a.setAttribute("opacity",
0)};d.appendChild(a)}function m(){var a=l.getCurrent(),b=l.getRoot(),k=[],m=d,n=besogo.svgEl("rect",{height:"100%",width:"100%","class":"besogo-svg-board besogo-svg-backer"});d=besogo.svgEl("svg");g=besogo.svgEl("g");p=besogo.svgEl("g");d.appendChild(n);d.appendChild(g);d.appendChild(p);b=c(b,0,0,k);p.appendChild(e(b,"black"));b=120*k.length;k=120*Math.max.apply(Math,k);d.setAttribute("viewBox","0 0 "+b+" "+k);d.setAttribute("height",.25*k);d.setAttribute("width",.25*b);m?h.replaceChild(d,m):h.appendChild(d);
f(a.navTreeMarker)}function c(f,g,h,l){var m=f.children,q;if(0===m.length)var n="m"+(120*g+60)+","+(120*h+60);else{var u=l[g+1]||0;u=u<h?h:u;h<u-1&&(h=u-1);n=c(m[0],g+1,u,l)+k(g,h,l);for(q=1;q<m.length;q++)u=l[g+1],u=c(m[q],g+1,u,l)+k(g,h,l,u-1),p.appendChild(e(u,"black"))}d.appendChild(b(f,g,h));a(f,g,h);l[g]=h+1;return n}function b(a,b,c){switch(a.getType()){case "move":var d=a.move.color;var e=besogo.svgEl("g");e.appendChild(besogo.svgStone(120*b+60,120*c+60,d));e.appendChild(besogo.svgLabel(120*
b+60,120*c+60,-1===d?"white":"black",""+a.moveNumber));break;case "setup":e=besogo.svgEl("g");e.appendChild(besogo.svgStone(120*b+60,120*c+60));e.appendChild(besogo.svgPlus(120*b+60,120*c+60,besogo.RED));break;default:e=besogo.svgStone(120*b+60,120*c+60)}a.navTreeIcon=e;a.navTreeX=b;a.navTreeY=c;return e}function a(a,b,c){b=besogo.svgEl("rect",{x:120*b+60-55,y:120*c+60-55,width:110,height:110,fill:besogo.TURQ});b.onclick=function(){l.setCurrent(a)};a.navTreeMarker=b;n(b)}function k(a,b,c,d){a=c[a+
1]-1;return a===b?"h-120":a===b+1?"l-120,-120":d&&d!==b?"l-60,-60v-"+120*(a-d):"l-60,-60v-"+120*(a-b-1)+"l-60,-60"}function e(a,b){return besogo.svgEl("path",{d:a,stroke:b,"stroke-width":8,fill:"none"})}var d,p,g,r;m();l.addListener(function(a){if(a.treeChange)m();else if(a.navChange)a=l.getCurrent(),n(r),f(a.navTreeMarker);else if(a.stoneChange){var c=l.getCurrent();a=c.navTreeIcon;c=b(c,c.navTreeX,c.navTreeY);d.replaceChild(c,a)}})};